global using System.Collections.Immutable;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics.CodeAnalysis;
global using System.Globalization;
global using Cofoundry.Core;
global using Cofoundry.Core.MessageAggregator;
global using Cofoundry.Core.Validation;
global using Cofoundry.Domain.CQS;
global using Microsoft.EntityFrameworkCore;
