//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]
[assembly: AssemblyInformationalVersion("0.1.0+3.Branch.master.Sha.e9244a0349c207423d2b6454957a34752cb56ae7")]
[assembly: AssemblyCopyright("Copyright © Cofoundry.org 2016")]

